# 工作流名称
name: GitHub-Profile-Summary-Cards

on:
  schedule:
    # Triggered every 24 hours
    - cron: "0 * * * *"
  # open this workflow manually
  workflow_dispatch:

jobs:
  # job id
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
